import type { LibrarySearchResult } from "./library-search";
import { resolveUserCompleteRitualContent } from "../practice/ritual-content";

function includesAny(value: string, needles: string[]): boolean {
  return needles.some((needle) => value.includes(needle));
}

const EKADASHI_SEARCH_ROUTES = [
  { observanceSlug: "aja-ekadashi", queryTerms: ["aja ekadashi", "annada ekadashi", "अजा एकादशी", "अन्नदा एकादशी"] },
  { observanceSlug: "parsva-ekadashi", queryTerms: ["parsva ekadashi", "parshva ekadashi", "parivartini ekadashi", "पार्श्व एकादशी", "परिवर्तिनी एकादशी"] },
  { observanceSlug: "indira-ekadashi", queryTerms: ["indira ekadashi", "इंदिरा एकादशी", "इन्दिरा एकादशी"] },
  { observanceSlug: "papankusha-ekadashi", queryTerms: ["papankusha ekadashi", "pashankusha ekadashi", "पापांकुशा एकादशी"] },
  { observanceSlug: "rama-ekadashi", queryTerms: ["rama ekadashi", "रमा एकादशी"] },
  { observanceSlug: "devutthana-ekadashi", queryTerms: ["devutthana ekadashi", "dev uthani ekadashi", "prabodhini ekadashi", "देवउठनी एकादशी", "प्रबोधिनी एकादशी"] },
  { observanceSlug: "utpanna-ekadashi", queryTerms: ["utpanna ekadashi", "उत्पन्ना एकादशी"] },
].map((entry) => ({
  ...entry,
  regionCode: "north-india",
  traditionCode: "smarta-north-india",
  sourceBoundary: "Complete only for the named, already calendar-resolved September-December 2026 Ekadashi devotional companion in the selected Smarta profile. The shared material-free form does not merge named stories, promises, Smarta and Vaishnava dates, fasting, food rules, medical guidance, unresolved Smarta parana, formal vrata, or every regional and sampradaya practice.",
}));

const WEEKDAY_SEARCH_ROUTES = [
  { observanceSlug: "weekday-ravivara", queryTerms: ["west india sunday practice", "mumbai sunday practice", "ravivara practice", "रविवार पश्चिम भारत"] },
  { observanceSlug: "weekday-somavara", queryTerms: ["west india monday practice", "mumbai monday practice", "somavara practice", "सोमवार पश्चिम भारत"] },
  { observanceSlug: "weekday-mangalavara", queryTerms: ["west india tuesday practice", "mumbai tuesday practice", "mangalavara practice", "मंगलवार पश्चिम भारत"] },
  { observanceSlug: "weekday-budhavara", queryTerms: ["west india wednesday practice", "mumbai wednesday practice", "budhavara practice", "बुधवार पश्चिम भारत"] },
  { observanceSlug: "weekday-guruvara", queryTerms: ["west india thursday practice", "mumbai thursday practice", "guruvara practice", "गुरुवार पश्चिम भारत"] },
  { observanceSlug: "weekday-shukravara", queryTerms: ["west india friday practice", "mumbai friday practice", "shukravara practice", "शुक्रवार पश्चिम भारत"] },
  { observanceSlug: "weekday-shanivara", queryTerms: ["west india saturday practice", "mumbai saturday practice", "shanivara practice", "शनिवार पश्चिम भारत"] },
].map((entry) => ({
  ...entry,
  regionCode: "west-india",
  traditionCode: "smarta-west-india",
  sourceBoundary: "Complete only for the named optional West India Smarta weekday lane. Family, kula, temple and sampradaya practice override it; other regional mappings, fasting, food or health guidance, astrological remedies, planetary appeasement, formal mantra and guaranteed outcomes remain outside this result.",
}));

const PITRU_PAKSHA_SEARCH_ROUTES = [
  { observanceSlug: "pitru-paksha-general", queryTerms: ["pitru paksha", "pitra paksha", "mahalaya paksha", "shraddha dates", "पितृ पक्ष", "श्राद्ध के दिन"] },
  { observanceSlug: "purnima-shraddha", queryTerms: ["purnima shraddha", "पूर्णिमा श्राद्ध"] },
  { observanceSlug: "pratipada-shraddha", queryTerms: ["pratipada shraddha", "प्रतिपदा श्राद्ध"] },
  { observanceSlug: "dwitiya-shraddha", queryTerms: ["dwitiya shraddha", "द्वितीया श्राद्ध"] },
  { observanceSlug: "tritiya-shraddha", queryTerms: ["tritiya shraddha", "तृतीया श्राद्ध"] },
  { observanceSlug: "maha-bharani", queryTerms: ["maha bharani", "महा भरणी"] },
  { observanceSlug: "chaturthi-shraddha", queryTerms: ["chaturthi shraddha", "चतुर्थी श्राद्ध"] },
  { observanceSlug: "panchami-shraddha", queryTerms: ["panchami shraddha", "पञ्चमी श्राद्ध", "पंचमी श्राद्ध"] },
  { observanceSlug: "shashthi-shraddha", queryTerms: ["shashthi shraddha", "षष्ठी श्राद्ध"] },
  { observanceSlug: "saptami-shraddha", queryTerms: ["saptami shraddha", "सप्तमी श्राद्ध"] },
  { observanceSlug: "ashtami-shraddha", queryTerms: ["ashtami shraddha", "अष्टमी श्राद्ध"] },
  { observanceSlug: "navami-shraddha", queryTerms: ["navami shraddha", "नवमी श्राद्ध"] },
  { observanceSlug: "dashami-shraddha", queryTerms: ["dashami shraddha", "दशमी श्राद्ध"] },
  { observanceSlug: "ekadashi-shraddha", queryTerms: ["ekadashi shraddha", "एकादशी श्राद्ध"] },
  { observanceSlug: "dwadashi-shraddha", queryTerms: ["dwadashi shraddha", "dvadasi shraddha", "द्वादशी श्राद्ध"] },
  { observanceSlug: "magha-shraddha", queryTerms: ["magha shraddha", "मघा श्राद्ध"] },
  { observanceSlug: "trayodashi-shraddha", queryTerms: ["trayodashi shraddha", "त्रयोदशी श्राद्ध"] },
  { observanceSlug: "chaturdashi-shraddha", queryTerms: ["chaturdashi shraddha", "चतुर्दशी श्राद्ध"] },
  { observanceSlug: "sarva-pitru-amavasya", queryTerms: ["sarva pitru amavasya", "mahalaya amavasya", "सर्वपितृ अमावस्या", "महालय अमावस्या"] },
].map((entry) => ({
  ...entry,
  regionCode: "north-india",
  traditionCode: "smarta-north-india",
  sourceBoundary: "Complete only for the bounded Delhi 2026 Pitru Paksha personal-remembrance and formal-practice preparation lane. The displayed day or label does not decide personal ancestor applicability, death-tithi, performer, Kutup/Rohina/Aparahna timing, mantra, pinda, tarpana, food, donation or priestly procedure; family and responsible religious authority control those decisions.",
}));

const RITUAL_SEARCH_ROUTES = [
  ...PITRU_PAKSHA_SEARCH_ROUTES,
  {
    queryTerms: ["kanya sankranti", "kanya sankramana", "कन्या संक्रांति"],
    observanceSlug: "kanya-sankranti",
    regionCode: "general-india",
    traditionCode: "family-specific-hindu",
    sourceBoundary: "Complete only for the bounded general personal Kanya Sankranti lane on the Delhi/India 17 September 2026 date. Punya kala, formal Surya worship, arghya, fasting, food, mantra, temple practice and regional forms require the user's location and authority; Bengal Vishwakarma Puja remains a separate lane.",
  },
  {
    queryTerms: ["tula sankranti", "tula sankramana", "तुला संक्रांति"],
    observanceSlug: "tula-sankranti",
    regionCode: "general-india",
    traditionCode: "family-specific-hindu",
    sourceBoundary: "Complete only for the bounded general personal Tula Sankranti lane on the Delhi/India 17 October 2026 date. Punya kala and fuller family or temple practice require local authority; Karnataka Kaveri Sankramana and Talakaveri Theerthodbhava remain a separate regional participant context.",
  },
  {
    queryTerms: ["vrishchika sankranti", "vrischika sankranti", "वृश्चिक संक्रांति"],
    observanceSlug: "vrishchika-sankranti",
    regionCode: "general-india",
    traditionCode: "family-specific-hindu",
    sourceBoundary: "Complete only for the bounded general personal Vrishchika Sankranti lane on the Delhi/India 16 November 2026 date. Punya kala, formal worship, fasting, food, mantra and every family, temple or regional form remain separately attributable.",
  },
  {
    queryTerms: ["dhanu sankranti", "dhanu sankramana", "धनु संक्रांति"],
    observanceSlug: "dhanu-sankranti",
    regionCode: "general-india",
    traditionCode: "family-specific-hindu",
    sourceBoundary: "Complete only for the bounded general personal Dhanu Sankranti lane on the Delhi/India 16 December 2026 date. Punya kala and fuller practice require local authority; Dhanu-named month, temple and regional observances are not automatically merged into this lane.",
  },
  {
    queryTerms: ["vishwakarma puja", "viswakarma puja", "bishwakarma puja", "biswakarma puja", "विश्वकर्मा पूजा", "বিশ্বকর্মা পূজা"],
    observanceSlug: "vishwakarma-puja-bengal",
    regionCode: "bengal",
    traditionCode: "regional-bengal",
    sourceBoundary: "Complete only for the bounded 17 September 2026 Bengal Vishwakarma Puja home, artisan and workplace-participation lane. The family, workplace, guild, temple or organiser controls formal liturgy; the responsible operator controls isolation and restart. Other regional Vishwakarma calendars and procedures remain separate.",
  },
  {
    queryTerms: ["maha ashtami", "mahashtami", "maha astami", "mahastami", "महाअष्टमी", "महा अष्टमी"],
    observanceSlug: "bengal-mahashtami-community-participant-2026",
    regionCode: "bengal",
    traditionCode: "shakta-bengal",
    sourceBoundary: "Complete only for the named 19 October 2026 Bengal Shakta participant lane; priest-led liturgy, household consecration, a universal Bengali procedure and live venue schedules remain outside this result.",
  },
  {
    queryTerms: ["bengal durga puja", "durga puja in bengal", "durga puja kolkata", "দুর্গা পূজা", "बंगाल दुर्गा पूजा", "कोलकाता दुर्गा पूजा"],
    observanceSlug: "bengal-durga-puja-campaign",
    regionCode: "bengal",
    traditionCode: "shakta-bengal",
    sourceBoundary: "Complete only for the named 16-21 October 2026 Bengal Shakta participant and remembrance lane. Family, bonedi bari, temple, Ramakrishna, community-pandal and visitor settings remain distinct; priest-led Puja, household consecration, live venue operations, immersion operations and every Bengal or Durga tradition remain outside this result.",
  },
  {
    queryTerms: ["ganesh chaturthi", "ganesha chaturthi", "ganapati festival", "ganeshotsav", "गणेश चतुर्थी", "गणेशोत्सव"],
    observanceSlug: "ganesh-chaturthi",
    regionCode: "west-india",
    traditionCode: "smarta-west-india",
    sourceBoundary: "Complete only for the named West India Smarta household Ganesh Chaturthi lane. Permanent and temporary images, family-chosen stay durations, temples and public pandals remain distinct; priest-led liturgy, all visarjan dates, every regional tradition and the complete Ganesha universe remain outside this result.",
  },
  {
    queryTerms: ["sankashti chaturthi", "sankashti", "sankat chauth", "sankatahara chaturthi", "संकष्टी चतुर्थी", "संकट चौथ", "संकटहर चतुर्थी"],
    observanceSlug: "sankashti-chaturthi-2026-09",
    regionCode: "west-india",
    traditionCode: "smarta-west-india",
    sourceBoundary: "Complete only for the four September-December 2026 West India Smarta Sankashti family lanes. The search result opens the September representative lane; the month, local moonrise and monthly identity must be selected separately. Fasting, katha, moon viewing, arghya, offerings, food, close, temple practice, Ganesh Chaturthi and Karwa Chauth are not universalized or merged.",
  },
  {
    queryTerms: ["shardiya navaratri", "sharadiya navaratri", "navratri ghatasthapana", "navaratri ghatasthapana", "शारदीय नवरात्रि", "नवरात्रि घटस्थापना"],
    observanceSlug: "shardiya-navaratri-begins",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the named North/West India Smarta household Shardiya Navaratri lane. Ghatasthapana is optional when it is not family practice; Bengal Durga Puja, Gujarati Garba, South Indian Kolu/Golu, Nepal Dashain, priest-led liturgy and the complete Devi tradition remain separate.",
  },
  {
    queryTerms: ["masika durgashtami", "masik durga ashtami", "monthly durga ashtami", "मासिक दुर्गाष्टमी", "मासिक दुर्गा अष्टमी"],
    observanceSlug: "masika-durgashtami-2026-09",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the four September-December 2026 North/West India Smarta monthly Durga-remembrance lanes. The search result opens the September representative lane. Formal Puja, fasting, Chandi recitation, Shardiya Mahashtami, Bengal Durga Puja and every Devi theology or regional Ashtami practice remain separate.",
  },
  {
    queryTerms: ["masika shivaratri", "masik shivratri", "monthly shivaratri", "मासिक शिवरात्रि"],
    observanceSlug: "masika-shivaratri-2026-09",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the four September-December 2026 North/West India Smarta Masika Shivaratri remembrance lanes. The search result opens the September representative lane. Formal puja, fasting, food rules, abhisheka, mantra counts, vigil, parana, annual Mahashivaratri, initiated Shaiva practice and every regional or temple form remain separate.",
  },
  {
    queryTerms: ["vasu baras", "vasubaras", "govatsa dwadashi", "govatsa dvadashi", "वसुबारस", "वसु बारस", "गोवत्स द्वादशी"],
    observanceSlug: "govatsa-dwadashi",
    regionCode: "west-india",
    traditionCode: "smarta-west-india",
    sourceBoundary: "Complete only for the named Maharashtra family Vasu Baras lane. Live-animal contact remains under the animal owner or trained keeper; Gujarat Wagh Baras, Bachha Baras, Guru Dwadashi, Nandini Vrat and other regional forms remain separate.",
  },
  {
    queryTerms: ["dhanteras", "dhantrayodashi", "dhanatrayodashi", "dhanvantari jayanti", "धनतेरस", "धनत्रयोदशी", "धन्वन्तरी जयंती"],
    observanceSlug: "dhantrayodashi",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the named North/West India Smarta household Dhantrayodashi lane. Shopping is optional; medical, financial and promised-outcome claims are excluded; Yama Deepam and every other Dhanteras tradition remain separate.",
  },
  {
    queryTerms: ["yama deepam", "yam deepam", "yama deep", "yam deep daan", "yama deepdan", "यम दीपम", "यम दीप", "यम दीपदान"],
    observanceSlug: "yama-deepam",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the named North/West India Smarta household Yama Deepam lane. Direction, lamp count, oil, wick, mantra, tarpan, and promised protection remain family- or source-specific; Dhantrayodashi worship is separate.",
  },
  {
    queryTerms: ["maharashtra naraka chaturdashi", "maharashtra narak chaturdashi", "maharashtra abhyanga snan", "mumbai abhyanga snan", "महाराष्ट्र नरक चतुर्दशी", "महाराष्ट्र अभ्यंग स्नान"],
    observanceSlug: "naraka-chaturdashi",
    regionCode: "west-india",
    traditionCode: "smarta-west-india",
    sourceBoundary: "Complete only for the named Maharashtra Smarta household Abhyanga-Snan lane. Oil and ubtan remain optional and suitability-dependent; Kali Chaudas, Tamil Deepavali, every Maharashtra family variant, and formal liturgy remain separate.",
  },
  {
    queryTerms: ["tamil deepavali", "tamil diwali", "tamil naraka chaturdashi", "tamil oil bath", "तमिल दीपावली", "तमिल नरक चतुर्दशी"],
    observanceSlug: "tamil-deepavali-naraka-chaturdashi",
    regionCode: "south-india",
    traditionCode: "smarta-south-india",
    sourceBoundary: "Complete only for the named Tamil/South India Smarta household morning lane. Oil, blessings, foods, prayers, clothing, and temple participation remain family-specific; North/West Lakshmi Puja and Maharashtra Naraka Chaturdashi are separate.",
  },
  {
    queryTerms: ["baps kali chaudas", "baps kali chaudash", "baps hanuman puja", "swaminarayan kali chaudas", "baps काली चौदस", "स्वामिनारायण काली चौदस"],
    observanceSlug: "kali-chaudas-baps",
    regionCode: "baps-gujarat",
    traditionCode: "swaminarayan-baps",
    sourceBoundary: "Complete only for the named BAPS Gujarat family- or mandir-participation lane. Formal Hanuman Puja remains with established BAPS authority; non-BAPS Gujarati traditions, Naraka Chaturdashi, Tamil Deepavali, and Bengali Kali Puja remain separate.",
  },
  {
    queryTerms: ["maharashtra bali pratipada", "maharashtra balipratipada", "maharashtra diwali padwa", "mumbai bali pratipada", "महाराष्ट्र बलि प्रतिपदा", "महाराष्ट्र दिवाली पाडवा"],
    observanceSlug: "bali-pratipada",
    regionCode: "west-india",
    traditionCode: "smarta-west-india",
    sourceBoundary: "Complete only for the named Maharashtra Smarta family Bali Pratipada/Padwa lane. Family, spouse, elder, business, temple, gift, meal and prayer customs remain household-specific; Govardhana/Annakut, Gujarati New Year and South Indian Balipadyami remain separate.",
  },
  {
    queryTerms: ["iskcon govardhan puja", "iskcon govardhana puja", "iskcon annakut", "iskcon bangalore govardhan", "इस्कॉन गोवर्धन पूजा", "इस्कॉन अन्नकूट"],
    observanceSlug: "govardhan-puja",
    regionCode: "iskcon-india",
    traditionCode: "vaishnava-iskcon",
    sourceBoundary: "Complete only for the named ISKCON Bangalore-aligned household or temple-participation lane. Formal liturgy, live programme, cow handling, large Annakut and prasadam operations remain with the institution; BAPS Annakut, Bali Pratipada and other Vaishnava or regional forms remain separate.",
  },
  {
    queryTerms: ["north india bhai dooj", "delhi bhai dooj", "north indian bhai dooj", "उत्तर भारत भाई दूज", "दिल्ली भाई दूज"],
    observanceSlug: "bhai-dooj",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the named North India Smarta household Bhai Dooj lane. Consent, family roles, tika materials, food, flame, gifts and reconciliation remain contextual; Bhau Beej, Bhai Phota, Bhai Tika and Bihar Yama Dwitiya require separate regional evidence.",
  },
  {
    queryTerms: ["bengal kali puja", "kolkata kali puja", "bengal shyama puja", "bengal mahanisha puja", "बंगाल काली पूजा", "कोलकाता काली पूजा"],
    observanceSlug: "bengal-kali-puja",
    regionCode: "bengal",
    traditionCode: "shakta-bengal",
    sourceBoundary: "Complete only for the named Bengal Shakta home, temple or public-puja participation lane. Formal liturgy, consecration, tantra, initiation, bali, homa, fasting, all-night vigil, live venue operations and every Bengal or Shakta lineage remain outside this result; West India Lakshmi Puja stays separate.",
  },
  {
    queryTerms: ["baps gujarati new year", "baps bestu varash", "baps nutan varsh", "swaminarayan gujarati new year", "BAPS गुजराती नववर्ष", "BAPS बेस्टु वर्ष"],
    observanceSlug: "gujarati-new-year-baps",
    regionCode: "baps-gujarat",
    traditionCode: "swaminarayan-baps",
    sourceBoundary: "Complete only for the named BAPS Gujarat family- or mandir-participation lane. Formal Annakut, thal, aarti, mantra, large food and prasadam operations remain with BAPS authority; business rites, non-BAPS New Year, Bali Pratipada, Govardhana Puja and Balipadyami stay separate.",
  },
  {
    queryTerms: ["karnataka saraswati puja", "karnataka saraswathi pooja", "ayudha puja karnataka", "ayudha pooja bengaluru", "mahanavami karnataka", "सरस्वती पूजा कर्नाटक", "आयुध पूजा कर्नाटक"],
    observanceSlug: "karnataka-saraswati-ayudha-puja",
    regionCode: "south-india",
    traditionCode: "smarta-south-india",
    sourceBoundary: "Complete only for the bounded 20 October 2026 Bengaluru/Karnataka Smarta household and established-programme participant lane. Formal mantras, consecration, homa, Vahana Puja, temple rites, workplace shutdowns, live machinery, and every Karnataka or South Indian variant remain with responsible living authority.",
  },
  {
    queryTerms: ["karnataka balipadyami", "karnataka bali padyami", "bengaluru balipadyami", "karnataka bali pratipada", "कर्नाटक बलि पाड्यमी", "कर्नाटक बलि प्रतिपदा"],
    observanceSlug: "karnataka-balipadyami",
    regionCode: "south-india",
    traditionCode: "smarta-south-india",
    sourceBoundary: "Complete only for the named Karnataka Smarta family- or temple-participation lane. A Bali representation is optional only when already known; formal temple rites, coastal procedures, prosperity claims, Maharashtra Padwa, BAPS New Year, Govardhana Puja and other Balipadyami traditions stay separate.",
  },
  {
    queryTerms: ["bandi chhor divas", "bandi chhod diwas", "guru hargobind 52 kings", "बंदी छोड़ दिवस", "ਗੁਰੂ ਹਰਿਗੋਬਿੰਦ ਬੰਦੀ ਛੋੜ"],
    observanceSlug: "bandi-chhor-divas-sgpc",
    regionCode: "sikh-punjab",
    traditionCode: "sikh-sgpc",
    sourceBoundary: "Complete only for the named SGPC-context personal, household, or gurdwara-participant lane. The local gurdwara controls paath, kirtan, ardas, Hukamnama, lighting, langar, seva, access, and schedule; Hindu and Jain Diwali remain separate.",
  },
  {
    queryTerms: ["ahoi ashtami", "ahoi aathe", "ahoi mata puja", "अहोई अष्टमी", "अहोई आठें", "अहोई माता पूजा"],
    observanceSlug: "ahoi-ashtami-north-india",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the named North India household lane. Family practice controls the fast, image, story, offerings, words, and star-or-moon close; Radha Kunda Krishnashtami and every regional or temple variant remain separate.",
  },
  {
    queryTerms: ["hartalika teej", "hartalika vrat", "hartalika puja", "हरतालिका तीज", "हरतालिका व्रत", "हरतालिका पूजा"],
    observanceSlug: "hartalika-teej",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the named North/West India Smarta participant and remembrance lane. The ordinary fast and formal household vrata are described but not prescribed; family, temple and living authorities retain sankalpa, katha, mantra, image worship, offerings and close. Hariyali Teej, Kajari Teej, Gowri Habba, Nepal and other regional forms remain separate.",
  },
  {
    queryTerms: ["radha ashtami", "radhashtami", "radhastami", "radharani appearance day", "राधा अष्टमी", "राधाष्टमी", "राधारानी प्राकट्य"],
    observanceSlug: "radha-ashtami-iskcon",
    regionCode: "iskcon-india",
    traditionCode: "vaishnava-iskcon",
    sourceBoundary: "Complete only for the named ISKCON India participant, home-remembrance, and official-temple-participation lane. Fasting and formal abhisheka, arati, homa, deity dressing, offerings, kalasha, flowers, bhoga, and Puja remain descriptive or under the user's own ISKCON authority; other Gaudiya Vaishnava, Vaishnava, Smarta, regional, family, and complete Radha Ashtami traditions remain separate.",
  },
  {
    queryTerms: ["gita jayanti", "geeta jayanti", "bhagavad gita jayanti", "gita jayanthi", "गीता जयंती", "गीता जयन्ती", "भगवद्गीता जयंती"],
    observanceSlug: "mokshada-ekadashi",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the bounded Gita Jayanti reading, reflection, and action lane on the supported 20 December 2026 Mokshada Ekadashi date. It requires an attributable edition and keeps source verse, translation, commentary, and personal application distinct; fasting, parana, temple liturgy, complete recitation, one universal interpretation, live-event operations, and the complete Gita or Ekadashi traditions remain outside this result.",
  },
  ...EKADASHI_SEARCH_ROUTES,
  ...WEEKDAY_SEARCH_ROUTES,
  {
    queryTerms: ["smarta janmashtami", "smarta krishna janmashtami", "स्मार्त जन्माष्टमी", "स्मार्त कृष्ण जन्माष्टमी"],
    observanceSlug: "krishna-janmashtami-smarta",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the bounded North India Smarta household Janmashtami lane. ISKCON authority and temple programmes, other regional traditions, fasting, food rules, midnight vigil, abhisheka, offerings, Dahi Handi, parana, and every Krishna textual or devotional tradition remain separate.",
  },
  {
    queryTerms: ["iskcon janmashtami", "iskcon krishna janmashtami", "इस्कॉन जन्माष्टमी", "इस्कॉन कृष्ण जन्माष्टमी"],
    observanceSlug: "krishna-janmashtami-iskcon",
    regionCode: "iskcon-india",
    traditionCode: "vaishnava-iskcon",
    sourceBoundary: "Complete only for the bounded ISKCON participant and accessible home-remembrance lane. Smarta rules, non-ISKCON Vaishnava traditions, formal temple abhisheka, arati, offerings, fasting, midnight operations, parana, Dahi Handi, and every Krishna textual or devotional tradition remain separate.",
  },
  {
    queryTerms: ["north india tulasi vivah", "smarta tulasi vivah", "north india tulsi vivah", "उत्तर भारत तुलसी विवाह", "स्मार्त तुलसी विवाह"],
    observanceSlug: "tulasi-vivah-dwadashi",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the bounded North/West India Smarta home-remembrance lane. The BAPS sequence, other Vaishnava and regional traditions, formal wedding liturgy, fasting, plant handling, purchases, marriage roles, and promised outcomes remain separate.",
  },
  {
    queryTerms: ["baps tulsi vivah", "baps tulasi vivah", "BAPS तुलसी विवाह"],
    observanceSlug: "tulsi-vivah-baps-begins",
    regionCode: "baps-gujarat",
    traditionCode: "swaminarayan-baps",
    sourceBoundary: "Complete only for the bounded BAPS November 21-24 participant sequence and accessible remembrance lane. The general Dwadashi lane, non-BAPS traditions, reconstructed institutional liturgy, fasting, plant handling, purchases, marriage roles, and promised outcomes remain separate.",
  },
  {
    queryTerms: ["vivaha panchami", "vivah panchami", "vivaha-panchami", "vivah-panchami", "विवाह पंचमी"],
    observanceSlug: "vivaha-panchami",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the named North India Smarta home-remembrance and reflection lane on the bounded 14 December 2026 Delhi date. Janakpur, Ayodhya, Orchha, family, temple, and public programmes remain distinct; a wedding reenactment, formal puja, mantra, offering, procession, vow, live-event operations, one universal Ramayana telling, and promised marriage or prosperity outcomes remain outside this result.",
  },
  {
    queryTerms: ["karwa chauth", "karva chauth", "karwa chauth vidhi", "करवा चौथ", "करवा चौथ विधि"],
    observanceSlug: "karwa-chauth",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the named North India household lane. Punjab and Uttar Pradesh sequences, the fast, Sargi, Bayaa, story, thali, karwa, sieve, moon offering, and close remain family- and health-contextual; no relationship or longevity outcome is promised.",
  },
  {
    queryTerms: ["chhath puja", "chhath vidhi", "sandhya arghya", "usha arghya", "छठ पूजा", "संध्या अर्घ्य", "उषा अर्घ्य"],
    observanceSlug: "chhath-puja-sandhya-arghya",
    regionCode: "bihar-purvanchal",
    traditionCode: "surya-chhath-bihar-purvanchal",
    sourceBoundary: "Complete only for the named Bihar/Purvanchal family participant and helper lane. The parvaitin and family control the vrata, fasting, food, purity, prasad, songs, Kosi, materials, and close; live ghat and safety operations remain current-authority concerns.",
  },
  {
    queryTerms: ["varanasi dev deepawali", "kashi dev deepawali", "varanasi dev diwali", "वाराणसी देव दीपावली", "काशी देव दीपावली"],
    observanceSlug: "dev-deepawali-varanasi",
    regionCode: "kashi-varanasi",
    traditionCode: "regional-kashi-varanasi",
    sourceBoundary: "Complete only for the named Varanasi home or public-event participant lane. Live Ganga Aarti, temple liturgy, river entry, floating lamps, boats, fireworks, access, routes, crowds, and schedules remain with current local authorities; generic Kartika Purnima stays separate.",
  },
  {
    queryTerms: ["lakshmi puja", "laxmi puja", "lakshmi pooja", "laxmi pooja", "lakshmi pujan", "लक्ष्मी पूजा", "लक्ष्मी-पूजन", "लक्ष्मी पूजन"],
    observanceSlug: "diwali-lakshmi-puja",
    regionCode: "west-india",
    traditionCode: "smarta-west-india",
    sourceBoundary: "Complete only for the named West India Smarta household Lakshmi Puja lane. Formal priest-led liturgy, a universal Diwali procedure, and Bengali Kali Puja, South Indian Deepavali, Jain Diwali, Bandi Chhor Divas and other regional traditions remain separate.",
  },
  {
    queryTerms: ["ananta chaturdashi", "anant chaturdashi", "अनन्त चतुर्दशी", "अनंत चतुर्दशी"],
    observanceSlug: "ananta-chaturdashi",
    regionCode: "west-india",
    traditionCode: "smarta-west-india",
    sourceBoundary: "Complete only for the named North/West India Smarta Ananta/Vishnu remembrance lane. Formal Ananta-vrata, fourteen-knot thread, kalasha, image, mantra, offerings, homa, fasting, promised outcomes, and the coincident Ganesh Visarjan procedure remain separate.",
  },
  {
    queryTerms: ["kalabhairava jayanti", "kaal bhairav jayanti", "kala bhairava jayanti", "कालभैरव जयंती", "काल भैरव जयंती"],
    observanceSlug: "kalabhairava-jayanti",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the bounded North India Smarta and Kashi regional Kalabhairava remembrance lane. Kashi temple identity remains regional; fast, tantra, mantra, offerings, intoxicants, animal offerings, occult or exorcistic rites, unsafe travel, and promised protection remain outside this result.",
  },
  {
    queryTerms: ["kojagara", "kojagiri", "sharad purnima", "कोजागरा", "कोजागिरी", "शरद पूर्णिमा"],
    observanceSlug: "kojagara-puja-sharad-purnima",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the bounded North/West India Smarta Kojagara/Sharad Purnima reflection lane. Bengali Kojagari Lakshmi Puja, next-day Ashwina Purnima, formal worship, fasting, moon worship, medicinal claims, gambling, vigil, unsafe food or flame, and promised outcomes remain separate.",
  },
  {
    queryTerms: ["rishi panchami", "ऋषि पंचमी"],
    observanceSlug: "rishi-panchami",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the bounded North/West India Smarta Saptarishi learning and gratitude lane. Multiple sage lists remain attributable; fasting, formal puja, atonement, impurity claims, women-only eligibility, Bhai Panchami, and promised purification remain outside this result.",
  },
  {
    queryTerms: ["pradosha", "pradosh vrat", "pradosham", "प्रदोष", "प्रदोष व्रत"],
    observanceSlug: "pradosha-2026-09-krishna",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the eight September-December 2026 North/West India Smarta Pradosha remembrance lanes. The result opens one representative occurrence; local Trayodashi twilight must be resolved separately. Fasting, puja muhurta, abhisheka, mantra, offering, Nandi practice, temple liturgy, parana, planetary remedies, and promised outcomes remain outside this result.",
  },
  {
    queryTerms: ["bhadrapada purnima", "ashwina purnima", "kartika purnima", "generic purnima", "purnima calendar day", "भाद्रपद पूर्णिमा", "आश्विन पूर्णिमा", "कार्तिक पूर्णिमा"],
    observanceSlug: "kartika-purnima",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the three resolved generic North/West India Smarta Purnima calendar-day companions. Named vratas, Kojagara, Sharad Purnima, Dev Deepawali, ritual bathing, moon worship, offerings, fasting, temple procedures, and promised outcomes remain separate. Margashirsha Purnima remains unresolved.",
  },
  {
    queryTerms: ["bhadrapada amavasya", "ashwina amavasya", "kartika amavasya", "margashirsha amavasya", "generic amavasya", "amavasya calendar day", "भाद्रपद अमावस्या", "आश्विन अमावस्या", "कार्तिक अमावस्या", "मार्गशीर्ष अमावस्या"],
    observanceSlug: "ashwina-amavasya",
    regionCode: "north-india",
    traditionCode: "smarta-north-india",
    sourceBoundary: "Complete only for the four resolved generic North/West India Smarta Amavasya calendar-day companions. Shraddha, tarpan, Darsha, ancestor rites, Diwali, temple or regional procedures, fasting, ritual bathing, offerings, and promised outcomes remain separate.",
  },
] as const;

export function searchUserCompleteRitualContent(query: string, languageCode?: string): LibrarySearchResult[] {
  const normalized = query.trim().toLocaleLowerCase("en");
  const route = RITUAL_SEARCH_ROUTES.find((candidate) => includesAny(normalized, [...candidate.queryTerms]));
  if (!route) return [];
  const hindi = languageCode?.toLowerCase().startsWith("hi") === true || /[\u0900-\u097f]/.test(query);
  const guide = resolveUserCompleteRitualContent({
    observanceSlug: route.observanceSlug,
    languageCode: hindi ? "hi" : "en",
    regionCode: route.regionCode,
    traditionCode: route.traditionCode,
  });
  if (!guide) return [];
  return [{
    id: `${guide.guideId}-exact-guidance`,
    title: guide.title,
    statement: [guide.summary, guide.familyPracticeNote].filter(Boolean).join(" "),
    languageCode: guide.languageCode,
    claimKind: "user_complete_observance_lane",
    citations: guide.evidence.sources.map((source, index) => ({
      passageId: `ritual-pack:${guide.evidence.packId}:${source.sourceId}`,
      sourceObjectId: source.sourceId,
      sourceOrdinal: index + 1,
      workTitle: source.title,
      editionTitle: source.publisher,
      locator: { source_role: source.sourceClass, pack_id: guide.evidence.packId },
      rightsLane: source.rightsLane === "derivative_allowed"
        ? "derivative_allowed"
        : source.rightsLane === "product_cleared" ? "product_allowed" : "citation_only",
    })),
    sourceBoundary: route.sourceBoundary,
  }];
}
