"""Compile the first Ramayana expected-story batch into a draft SQL projection."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Callable


ROOT = Path(__file__).resolve().parents[1]
PACK = ROOT / "knowledge_packs/library_lanes/ramayana/expected-stories-beginnings-exile-v1.json"
OUTPUT = ROOT / "supabase/migrations/20260813130000_seed_ramayana_expected_stories_beginnings_exile.sql"
CONTRACT = "DEVAM_RAMAYANA_EXPECTED_STORIES_BEGINNINGS_EXILE_V1"
SERIES_SLUG = "ramcharitmanas-expected-stories-beginnings-exile-v1"
SNAPSHOT = "DEVAM_RAMAYANA_EXPECTED_STORIES_BEGINNINGS_EXILE_DB_V1"
WORK_SLUG = "tulsidas-ramcharitmanas"
EXPRESSION_KIND = "fixed_scan_alignment"
EXPRESSION_ATTRIBUTION = "Belvedere Press second-edition fixed scan; Devam expected-story alignment v1"


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def json_sql(value: object) -> str:
    return sql_quote(json.dumps(value, ensure_ascii=False, separators=(",", ":"))) + "::jsonb"


def load_pack() -> dict:
    data = json.loads(PACK.read_text(encoding="utf-8"))
    if data.get("contract") != CONTRACT or data.get("version") != 1:
        raise ValueError("expected-story batch contract drift")
    stories = data.get("stories", [])
    if len(stories) != 7 or len({row["expectation_id"] for row in stories}) != 7:
        raise ValueError("expected-story batch must contain exactly seven unique stories")
    if any(row.get("consumer_state") != "consumer_complete_en_hi" for row in stories):
        raise ValueError("all projected stories must be consumer_complete_en_hi")
    if sum(len(row["episodes"]) for row in stories) != 69:
        raise ValueError("expected-story episode denominator drift")
    return data


def compile_sql(
    data: dict,
    *,
    series_slug: str = SERIES_SLUG,
    snapshot: str = SNAPSHOT,
    arcs: list[tuple[str, int, str, str]] | None = None,
    series_title: str = "Ramcharitmanas expected stories: beginnings and exile",
    series_boundary: str = "Seven source-aligned consumer stories from labelled Ramcharitmanas ranges. This is not a complete Ramcharitmanas story map, every Rama tradition, or the selected Dutt expression.",
    work_spec: dict[str, object] | None = None,
    source_range_factory: Callable[[dict, dict, str], dict] | None = None,
    beat_source_range_factory: Callable[[dict, dict, dict, str], dict] | None = None,
    include_passage_evidence: bool = True,
    projection_label: str = "Ramcharitmanas supplement",
    check_label: str = "Ramcharitmanas expected stories",
    beat_check_label: str = "Ramcharitmanas expected-story",
    total_source_units: int | None = None,
    link_label: str = "source-ordered expected-story traversal",
) -> str:
    stories = data["stories"]
    if arcs is None:
        arcs = [("beginnings", 1, "Beginnings", "आरंभ"), ("exile", 2, "Exile", "वनवास")]
    if work_spec is None:
        work_spec = {
            "slug": WORK_SLUG,
            "canonical_title": "रामचरितमानस (Ramcharitmanas)",
            "work_kind": "devotional_epic",
            "tradition_scope": ["Sanatana Dharma", "Rama bhakti"],
            "summary": "Tulsidas's principally Awadhi retelling of the Rama narrative; this row is a compact alignment prerequisite, not a completeness claim.",
            "language_code": "awa",
            "script_code": "Deva",
            "expression_kind": EXPRESSION_KIND,
            "attribution": EXPRESSION_ATTRIBUTION,
            "is_source_original": True,
            "ai_generated": False,
        }
    work_slug = str(work_spec["slug"])
    expression_kind = str(work_spec["expression_kind"])
    expression_attribution = str(work_spec["attribution"])
    language_code = str(work_spec["language_code"])
    if total_source_units is None:
        total_source_units = int(data["batch_counters"]["source_scan_page_union_count"])
    story_count = len(stories)
    beat_count = sum(len(row["episodes"]) for row in stories)
    story_text_count = story_count * 2
    beat_text_count = beat_count * 2
    lines = [
        "-- Generated by tools/compile_ramayana_expected_story_batch.py.",
        "-- Compact Devam-authored bilingual narration only; no source-vault bytes are copied.",
        f"-- The series is a bounded {'seven' if story_count == 7 else story_count}-story {projection_label}, not the whole work or every Ramayana.",
        "",
        "begin;",
        "",
        "-- Make the bounded projection self-contained on a fresh database. These rows",
        "-- describe the aligned work/expression only; they do not publish or copy source bytes.",
        "insert into public.works (slug, canonical_title, work_kind, tradition_scope, summary, rights_lane, publication_state)",
        "values (",
        f"  {sql_quote(work_slug)}, {sql_quote(str(work_spec['canonical_title']))}, {sql_quote(str(work_spec['work_kind']))},",
        "  array[" + ", ".join(sql_quote(str(value)) for value in work_spec["tradition_scope"]) + "],",
        f"  {sql_quote(str(work_spec['summary']))},",
        "  'derivative_allowed', 'draft'",
        ")",
        "on conflict (slug) do nothing;",
        "",
        "insert into public.expressions (",
        "  work_id, language_code, script_code, expression_kind, attribution, is_source_original, ai_generated, rights_lane, publication_state",
        ")",
        f"select work.id, {sql_quote(language_code)}, {sql_quote(str(work_spec['script_code']))},",
        f"  {sql_quote(expression_kind)}, {sql_quote(expression_attribution)}, {str(bool(work_spec['is_source_original'])).lower()}, {str(bool(work_spec['ai_generated'])).lower()}, 'derivative_allowed', 'draft'",
        "from public.works work",
        f"where work.slug = {sql_quote(work_slug)}",
        "on conflict (work_id, language_code, expression_kind, attribution) do nothing;",
        "",
        "insert into public.narrative_series (",
        "  slug, expression_id, canonical_title, narrative_kind, selected_expression_boundary,",
        "  total_source_units, coverage_state, rights_lane, publication_state",
        ")",
        "select",
        f"  {sql_quote(series_slug)}, expression.id, {sql_quote(series_title)},",
        "  'epic',",
        f"  {sql_quote(series_boundary)},",
        f"  {total_source_units}, 'consumer_complete_selected_expression', 'derivative_allowed', 'draft'",
        "from public.expressions expression",
        "join public.works work on work.id = expression.work_id",
        f"where work.slug = {sql_quote(work_slug)}",
        f"  and expression.language_code = {sql_quote(language_code)}",
        f"  and expression.expression_kind = {sql_quote(expression_kind)}",
        f"  and expression.attribution = {sql_quote(expression_attribution)}",
        "on conflict (slug) do update set",
        "  expression_id = excluded.expression_id, canonical_title = excluded.canonical_title,",
        "  narrative_kind = excluded.narrative_kind, selected_expression_boundary = excluded.selected_expression_boundary,",
        "  total_source_units = excluded.total_source_units, coverage_state = excluded.coverage_state,",
        "  rights_lane = excluded.rights_lane, publication_state = excluded.publication_state, updated_at = now();",
        "",
    ]

    arc_values = []
    for slug, ordinal, en, hi in arcs:
        story_ids = [row["story_id"] for row in stories if row["sequence_group"] == slug]
        source_range = {"snapshotContract": snapshot, "storyIds": story_ids}
        arc_values.append(f"  ({sql_quote(slug)}, {ordinal}, {sql_quote(en)}, {json_sql(source_range)})")
    lines.extend(
        [
            "insert into public.narrative_arcs (series_id, slug, arc_ordinal, canonical_title, source_range, rights_lane, publication_state)",
            "select series.id, source.slug, source.ordinal, source.title, source.source_range, 'derivative_allowed', 'draft'",
            "from (values",
            ",\n".join(arc_values),
            ") as source(slug, ordinal, title, source_range)",
            f"join public.narrative_series series on series.slug = {sql_quote(series_slug)}",
            "on conflict (series_id, slug) do update set arc_ordinal=excluded.arc_ordinal, canonical_title=excluded.canonical_title,",
            "  source_range=excluded.source_range, rights_lane=excluded.rights_lane, publication_state=excluded.publication_state, updated_at=now();",
            "",
        ]
    )

    arc_text_values = []
    for slug, _, en, hi in arcs:
        if slug == "beginnings":
            invitation_en = "Enter the antecedents and familiar scenes before Rama's exile"
            invitation_hi = "राम के वनवास से पहले की पूर्वकथाओं और परिचित प्रसंगों में प्रवेश करें"
        elif slug == "exile":
            invitation_en = "Cross the Ganga with Rama, Sita and Lakshmana"
            invitation_hi = "राम, सीता और लक्ष्मण के साथ गंगा पार करें"
        else:
            invitation_en = f"Follow the complete {en.casefold()} story sequence"
            invitation_hi = f"{hi} की पूरी कथा-श्रृंखला के साथ आगे बढ़ें"
        arc_text_values.extend(
            [
                f"  ({sql_quote(slug)}, 'en', {sql_quote(en)}, {sql_quote(invitation_en)})",
                f"  ({sql_quote(slug)}, 'hi', {sql_quote(hi)}, {sql_quote(invitation_hi)})",
            ]
        )
    lines.extend(
        [
            "insert into public.narrative_arc_texts (arc_id, language_code, title, invitation, text_status, rights_lane, publication_state)",
            "select arc.id, source.language_code, source.title, source.invitation, 'source_aligned', 'derivative_allowed', 'draft'",
            "from (values",
            ",\n".join(arc_text_values),
            ") as source(arc_slug, language_code, title, invitation)",
            f"join public.narrative_series series on series.slug = {sql_quote(series_slug)}",
            "join public.narrative_arcs arc on arc.series_id=series.id and arc.slug=source.arc_slug",
            "on conflict (arc_id, language_code) do update set title=excluded.title, invitation=excluded.invitation,",
            "  text_status=excluded.text_status, rights_lane=excluded.rights_lane, publication_state=excluded.publication_state, updated_at=now();",
            "",
            "delete from public.narrative_moments moment using public.narrative_series series",
            f"where moment.series_id=series.id and series.slug={sql_quote(series_slug)}",
            f"  and moment.source_range->>'snapshotContract'={sql_quote(snapshot)};",
            "",
        ]
    )

    moment_values = []
    arc_ordinals = {slug: 0 for slug, _, _, _ in arcs}
    for backbone_ordinal, story in enumerate(stories, 1):
        arc_ordinals[story["sequence_group"]] += 1
        alignment = story["source_alignment"]
        if source_range_factory is None:
            source_range = {
                "snapshotContract": snapshot,
                "expectationId": story["expectation_id"],
                "storyId": story["story_id"],
                "sourceId": alignment["source_id"],
                "scanSha256": data["source_registry"][0]["scan_sha256"],
                "kanda": alignment["kanda"],
                "scanPagesInclusive": alignment["scan_pages_inclusive"],
                "dohaRangeInclusive": alignment["doha_range_inclusive"],
                "secondaryLocator": alignment["secondary_locator"],
            }
        else:
            source_range = source_range_factory(data, story, snapshot)
        visual = {
            "readiness": "consumer_complete_en_hi",
            "characters": story["characters"],
            "places": story["places"],
            "relationships": story["relationships"],
            "expressionScope": story["expression_scope"],
        }
        moment_values.append(
            "  (" + ", ".join(
                [
                    sql_quote(story["story_id"]),
                    sql_quote(story["sequence_group"]),
                    str(backbone_ordinal),
                    str(arc_ordinals[story["sequence_group"]]),
                    json_sql(source_range),
                    json_sql(visual),
                ]
            ) + ")"
        )
    lines.extend(
        [
            "insert into public.narrative_moments (series_id, arc_id, slug, moment_kind, backbone_ordinal, turn_ordinal_in_arc, detail_ordinal, source_range, compression_note, visual_direction, rights_lane, publication_state)",
            "select series.id, arc.id, source.slug, 'backbone_turn', source.backbone_ordinal, source.turn_ordinal, 0, source.source_range,",
            "  'Complete bilingual source-aligned expected-story sequence; not a selected-Dutt-expression claim.', source.visual_direction, 'derivative_allowed', 'draft'",
            "from (values",
            ",\n".join(moment_values),
            ") as source(slug, arc_slug, backbone_ordinal, turn_ordinal, source_range, visual_direction)",
            f"join public.narrative_series series on series.slug={sql_quote(series_slug)}",
            "join public.narrative_arcs arc on arc.series_id=series.id and arc.slug=source.arc_slug",
            "on conflict (series_id, slug) do update set arc_id=excluded.arc_id, moment_kind=excluded.moment_kind, backbone_ordinal=excluded.backbone_ordinal,",
            "  turn_ordinal_in_arc=excluded.turn_ordinal_in_arc, detail_ordinal=excluded.detail_ordinal, source_range=excluded.source_range,",
            "  compression_note=excluded.compression_note, visual_direction=excluded.visual_direction, rights_lane=excluded.rights_lane, publication_state=excluded.publication_state, updated_at=now();",
            "",
        ]
    )

    moment_text_values = []
    for story in stories:
        for language in ("en", "hi"):
            narration = "\n\n".join(episode["narration"][language] for episode in story["episodes"])
            synopsis = story["episodes"][0]["narration"][language] + " " + story["transition"][language]
            moment_text_values.append(
                f"  ({sql_quote(story['story_id'])}, {sql_quote(language)}, {sql_quote(story['title'][language])}, {sql_quote(synopsis)}, {sql_quote(narration)})"
            )
    lines.extend(
        [
            "insert into public.narrative_moment_texts (moment_id, language_code, title, synopsis, narrative, text_status, rights_lane, publication_state)",
            "select moment.id, source.language_code, source.title, source.synopsis, source.narrative, 'source_aligned', 'derivative_allowed', 'draft'",
            "from (values",
            ",\n".join(moment_text_values),
            ") as source(moment_slug, language_code, title, synopsis, narrative)",
            f"join public.narrative_series series on series.slug={sql_quote(series_slug)}",
            "join public.narrative_moments moment on moment.series_id=series.id and moment.slug=source.moment_slug",
            "on conflict (moment_id, language_code) do update set title=excluded.title, synopsis=excluded.synopsis, narrative=excluded.narrative,",
            "  text_status=excluded.text_status, rights_lane=excluded.rights_lane, publication_state=excluded.publication_state, updated_at=now();",
            "",
        ]
    )

    beat_values = []
    beat_text_values = []
    for story in stories:
        for episode in story["episodes"]:
            if beat_source_range_factory is None:
                source_range = {
                    "snapshotContract": snapshot,
                    "storyId": story["story_id"],
                    "sourceId": story["source_alignment"]["source_id"],
                    "scanSha256": data["source_registry"][0]["scan_sha256"],
                    "scanPages": episode["source_scan_pages"],
                }
            else:
                source_range = beat_source_range_factory(data, story, episode, snapshot)
            beat_values.append(
                f"  ({sql_quote(story['story_id'])}, {sql_quote(episode['episode_id'])}, {episode['ordinal']}, {json_sql(source_range)})"
            )
            for language in ("en", "hi"):
                beat_text_values.append(
                    f"  ({sql_quote(story['story_id'])}, {sql_quote(episode['episode_id'])}, {sql_quote(language)}, {sql_quote(episode['title'][language])}, {sql_quote(episode['narration'][language])})"
                )
    lines.extend(
        [
            "insert into public.narrative_beats (moment_id, slug, beat_ordinal, source_range, visual_direction, rights_lane, publication_state)",
            "select moment.id, source.beat_slug, source.beat_ordinal, source.source_range, '{}'::jsonb, 'derivative_allowed', 'draft'",
            "from (values",
            ",\n".join(beat_values),
            ") as source(moment_slug, beat_slug, beat_ordinal, source_range)",
            f"join public.narrative_series series on series.slug={sql_quote(series_slug)}",
            "join public.narrative_moments moment on moment.series_id=series.id and moment.slug=source.moment_slug",
            "on conflict (moment_id, slug) do update set beat_ordinal=excluded.beat_ordinal, source_range=excluded.source_range,",
            "  visual_direction=excluded.visual_direction, rights_lane=excluded.rights_lane, publication_state=excluded.publication_state, updated_at=now();",
            "",
            "insert into public.narrative_beat_texts (beat_id, language_code, title, narration, text_status, rights_lane, publication_state)",
            "select beat.id, source.language_code, source.title, source.narration, 'source_aligned', 'derivative_allowed', 'draft'",
            "from (values",
            ",\n".join(beat_text_values),
            ") as source(moment_slug, beat_slug, language_code, title, narration)",
            f"join public.narrative_series series on series.slug={sql_quote(series_slug)}",
            "join public.narrative_moments moment on moment.series_id=series.id and moment.slug=source.moment_slug",
            "join public.narrative_beats beat on beat.moment_id=moment.id and beat.slug=source.beat_slug",
            "on conflict (beat_id, language_code) do update set title=excluded.title, narration=excluded.narration, text_status=excluded.text_status,",
            "  rights_lane=excluded.rights_lane, publication_state=excluded.publication_state, updated_at=now();",
            "",
        ]
    )

    link_values = []
    for left, right in zip(stories, stories[1:]):
        link_values.extend(
            [
                f"  ({sql_quote(left['story_id'])}, {sql_quote(right['story_id'])}, 'precedes')",
                f"  ({sql_quote(right['story_id'])}, {sql_quote(left['story_id'])}, 'follows')",
            ]
        )
    lines.extend(
        [
            "insert into public.narrative_moment_links (source_moment_id, target_moment_id, link_kind, label)",
            f"select source_moment.id, target_moment.id, source.link_kind, {sql_quote(link_label)}",
            "from (values",
            ",\n".join(link_values),
            ") as source(source_slug, target_slug, link_kind)",
            f"join public.narrative_series series on series.slug={sql_quote(series_slug)}",
            "join public.narrative_moments source_moment on source_moment.series_id=series.id and source_moment.slug=source.source_slug",
            "join public.narrative_moments target_moment on target_moment.series_id=series.id and target_moment.slug=source.target_slug",
            "on conflict (source_moment_id, target_moment_id, link_kind) do update set label=excluded.label;",
            "",
        ]
    )
    if include_passage_evidence:
        lines.extend(
            [
            "insert into public.narrative_evidence (moment_id, passage_id, evidence_role, note)",
            "select moment.id, passage.id, 'source_span', 'Pinned Ramcharitmanas page within the exact story scan range'",
            "from public.narrative_series series",
            "join public.narrative_moments moment on moment.series_id=series.id",
            "join public.passages passage on passage.locator->>'scan_sha256'=moment.source_range->>'scanSha256'",
            "  and (passage.locator->>'scan_page')::integer between (moment.source_range->'scanPagesInclusive'->>0)::integer",
            "  and (moment.source_range->'scanPagesInclusive'->>1)::integer",
            f"where series.slug={sql_quote(series_slug)}",
            "on conflict (moment_id, beat_id, passage_id, evidence_role) do update set note=excluded.note;",
            "",
            ]
        )
    lines.extend(
        [
            "do $devam$",
            "declare story_count integer; beat_count integer; bilingual_story_text_count integer; bilingual_beat_text_count integer;",
            "begin",
            "  select count(*) into story_count from public.narrative_moments moment join public.narrative_series series on series.id=moment.series_id",
            f"  where series.slug={sql_quote(series_slug)} and moment.source_range->>'snapshotContract'={sql_quote(snapshot)};",
            "  select count(*) into beat_count from public.narrative_beats beat join public.narrative_moments moment on moment.id=beat.moment_id",
            f"  join public.narrative_series series on series.id=moment.series_id where series.slug={sql_quote(series_slug)};",
            "  select count(*) into bilingual_story_text_count from public.narrative_moment_texts text join public.narrative_moments moment on moment.id=text.moment_id",
            f"  join public.narrative_series series on series.id=moment.series_id where series.slug={sql_quote(series_slug)};",
            "  select count(*) into bilingual_beat_text_count from public.narrative_beat_texts text join public.narrative_beats beat on beat.id=text.beat_id",
            "  join public.narrative_moments moment on moment.id=beat.moment_id join public.narrative_series series on series.id=moment.series_id",
            f"  where series.slug={sql_quote(series_slug)};",
            f"  if story_count <> {story_count} then raise exception 'Expected {story_count} {check_label}, got %', story_count; end if;",
            f"  if beat_count <> {beat_count} then raise exception 'Expected {beat_count} {beat_check_label} beats, got %', beat_count; end if;",
            f"  if bilingual_story_text_count <> {story_text_count} then raise exception 'Expected {story_text_count} bilingual story texts, got %', bilingual_story_text_count; end if;",
            f"  if bilingual_beat_text_count <> {beat_text_count} then raise exception 'Expected {beat_text_count} bilingual beat texts, got %', bilingual_beat_text_count; end if;",
            "end",
            "$devam$;",
            "",
            "commit;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = compile_sql(load_pack())
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("Ramayana expected-story migration is stale; run the compiler")
        print("PASS: Ramayana expected-story migration is current")
        return
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
