-- Generated by tools/compile_devimahatmya_semantic_graph_v1.py.
-- Source-bounded semantic indexing only; no source payload is copied.

begin;

do $$
begin
  if (select count(*) from public.entities where slug='devi-mahatmya' and publication_state='published') <> 1 then
    raise exception 'Published Devimahatmya subject entity is absent or duplicated';
  end if;
  if (select count(*) from public.source_objects where sha256='c7fe701aedeedffde57a51b21aa4f8fec697a7922939fb59ffa985e22cc9b7ae' and rights_lane='derivative_allowed') <> 1 then
    raise exception 'Pinned Devimahatmya source object is absent, duplicated, or rights-incompatible';
  end if;
  if (select count(*) from public.passages where source_object_id=(select id from public.source_objects where sha256='c7fe701aedeedffde57a51b21aa4f8fec697a7922939fb59ffa985e22cc9b7ae') and source_ordinal in (68, 189, 229) and publication_state='published' and rights_lane='derivative_allowed') <> 3 then
    raise exception 'Pinned semantic evidence passage set is incomplete';
  end if;
end $$;

with input(slug, entity_kind, canonical_name, description) as (values
  ('madhu-kaitabha', 'narrative_pair', 'Madhu and Kaiṭabha', 'A paired narrative identity indexed only within the exact pinned Devī Māhātmya source universe.'),
  ('mahishasura', 'narrative_figure', 'Mahiṣāsura', 'A narrative figure indexed only within the exact pinned Devī Māhātmya source universe.'),
  ('shumbha', 'narrative_figure', 'Śumbha', 'A narrative figure indexed only within the exact pinned Devī Māhātmya source universe.'),
  ('nishumbha', 'narrative_figure', 'Niśumbha', 'A narrative figure indexed only within the exact pinned Devī Māhātmya source universe.')
)
insert into public.entities (slug, entity_kind, canonical_name, description, temporal_scope, geographic_scope, rights_lane, publication_state)
select slug, entity_kind, canonical_name, description, '{}'::jsonb, '{}'::jsonb, 'derivative_allowed', 'published' from input
on conflict (slug) do update set entity_kind=excluded.entity_kind, canonical_name=excluded.canonical_name, description=excluded.description, temporal_scope=excluded.temporal_scope, geographic_scope=excluded.geographic_scope, rights_lane=excluded.rights_lane, publication_state=excluded.publication_state;

with input(entity_slug, name, language_code, script_code, name_kind, is_preferred) as (values
  ('madhu-kaitabha', 'Madhu and Kaiṭabha', 'en', 'Latn', 'preferred', true),
  ('madhu-kaitabha', 'मधु और कैटभ', 'hi', 'Deva', 'preferred', true),
  ('madhu-kaitabha', 'मधुकैटभ', 'sa', 'Deva', 'preferred', true),
  ('mahishasura', 'Mahiṣāsura', 'en', 'Latn', 'preferred', true),
  ('mahishasura', 'महिषासुर', 'hi', 'Deva', 'preferred', true),
  ('mahishasura', 'महिषासुर', 'sa', 'Deva', 'preferred', true),
  ('shumbha', 'Śumbha', 'en', 'Latn', 'preferred', true),
  ('shumbha', 'शुम्भ', 'hi', 'Deva', 'preferred', true),
  ('shumbha', 'शुम्भ', 'sa', 'Deva', 'preferred', true),
  ('nishumbha', 'Niśumbha', 'en', 'Latn', 'preferred', true),
  ('nishumbha', 'निशुम्भ', 'hi', 'Deva', 'preferred', true),
  ('nishumbha', 'निशुम्भ', 'sa', 'Deva', 'preferred', true)
)
insert into public.entity_names (entity_id, name, language_code, script_code, name_kind, is_preferred)
select e.id, i.name, i.language_code, i.script_code, i.name_kind, i.is_preferred
from input i join public.entities e on e.slug=i.entity_slug
on conflict (entity_id, name, language_code, name_kind) do update set script_code=excluded.script_code, is_preferred=excluded.is_preferred;

with input(stable_key, statement, language_code, confidence, citation_ordinal, chapter, verse, source_ordinal, source_span_sha256, translation_note, uncertainty_note) as (values
  ('durga-devimahatmya-semantic-madhu-kaitabha-episode-en', 'Within this exact provider-revision boundary, Devī Māhātmya chapter 81 presents the narrative of the Goddess acting so that Madhu and Kaiṭabha might be slain.', 'en', 0.9, 68, 81, 68, 68, '9674ccdc9085abf16771972b1a0baf50062d4fb67a85864a5a1330d105d9ce3e', 'Tāmasī is translated as dark while retaining the Sanskrit category in Hindi; it should not be reduced to a moral judgment.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 81, verse 68. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-madhu-kaitabha-episode-hi', 'इस सटीक प्रदाता-संशोधन सीमा में देवीमाहात्म्य का अध्याय 81 देवी द्वारा मधु और कैटभ के वध की दिशा में किए गए कार्य का आख्यान प्रस्तुत करता है।', 'hi', 0.9, 68, 81, 68, 68, '9674ccdc9085abf16771972b1a0baf50062d4fb67a85864a5a1330d105d9ce3e', 'Tāmasī is translated as dark while retaining the Sanskrit category in Hindi; it should not be reduced to a moral judgment.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 81, verse 68. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-mahishasura-episode-en', 'Within this exact provider-revision boundary, Devī Māhātmya chapter 83 presents the Goddess''s destruction of Mahiṣa together with his army and allies.', 'en', 0.97, 189, 83, 41, 189, '0acdefb9b761bf80c8c2d9a31f26859889e3c67dcf77646e312284e4215acda3', 'The narrative’s trilokya-delusion claim remains explicitly attributed to this source.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 83, verse 41. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-mahishasura-episode-hi', 'इस सटीक प्रदाता-संशोधन सीमा में देवीमाहात्म्य का अध्याय 83 देवी द्वारा महिष, उसकी सेना और उसके सहयोगियों के विनाश का आख्यान प्रस्तुत करता है।', 'hi', 0.97, 189, 83, 41, 189, '0acdefb9b761bf80c8c2d9a31f26859889e3c67dcf77646e312284e4215acda3', 'The narrative’s trilokya-delusion claim remains explicitly attributed to this source.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 83, verse 41. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-shumbha-episode-en', 'Within this exact provider-revision boundary, Devī Māhātmya chapter 84 introduces the Goddess''s renewed manifestation for the slaying of Śumbha.', 'en', 0.98, 229, 84, 37, 229, '6942ec592593a86e4d6b94c5fddd009b9a90f79f720f42c473b2194f3269fbd4', 'The source names the next manifestation’s bodily origin and adversaries, defining the transition to the following episode.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 84, verse 37. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-shumbha-episode-hi', 'इस सटीक प्रदाता-संशोधन सीमा में देवीमाहात्म्य का अध्याय 84 शुम्भ के वध के लिए देवी के पुनः प्रकट होने का आख्यान आरम्भ करता है।', 'hi', 0.98, 229, 84, 37, 229, '6942ec592593a86e4d6b94c5fddd009b9a90f79f720f42c473b2194f3269fbd4', 'The source names the next manifestation’s bodily origin and adversaries, defining the transition to the following episode.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 84, verse 37. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-nishumbha-episode-en', 'Within this exact provider-revision boundary, Devī Māhātmya chapter 84 introduces the Goddess''s renewed manifestation for the slaying of Niśumbha.', 'en', 0.98, 229, 84, 37, 229, '6942ec592593a86e4d6b94c5fddd009b9a90f79f720f42c473b2194f3269fbd4', 'The source names the next manifestation’s bodily origin and adversaries, defining the transition to the following episode.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 84, verse 37. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-nishumbha-episode-hi', 'इस सटीक प्रदाता-संशोधन सीमा में देवीमाहात्म्य का अध्याय 84 निशुम्भ के वध के लिए देवी के पुनः प्रकट होने का आख्यान आरम्भ करता है।', 'hi', 0.98, 229, 84, 37, 229, '6942ec592593a86e4d6b94c5fddd009b9a90f79f720f42c473b2194f3269fbd4', 'The source names the next manifestation’s bodily origin and adversaries, defining the transition to the following episode.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 84, verse 37. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.')
)
insert into public.claims (stable_key, subject_entity_id, statement, language_code, claim_kind, evidence_class, confidence, applicability, uncertainty_note, rights_lane, publication_state)
select i.stable_key, subject.id, i.statement, i.language_code, 'source_bounded_narrative_index', 'devam_synthesis', i.confidence,
  jsonb_build_object('pack_id', 'durga-devimahatmya-semantic-graph-v1', 'pack_sha256', '0dcd7f37ebdcb3dc5ad4049aafa0cb5b7668884bbb29e6b742e32fe7a0b75c34', 'work_slug', 'markandeya-purana',
    'bounded_text', 'devimahatmya_chapters_81_93', 'source_profile_id', 'devimahatmya-wikisource-sanskrit-v1', 'provider', 'Sanskrit Wikisource',
    'citation_ordinal', i.citation_ordinal, 'chapter', i.chapter, 'verse', i.verse, 'scope', 'this_exact_three_revision_source_universe_only',
    'translation_status', 'devam_beta_source_aligned_not_independently_sanskrit_reviewed', 'translation_is_source_original', false),
  i.uncertainty_note, 'derivative_allowed', 'published'
from input i cross join public.entities subject where subject.slug='devi-mahatmya'
on conflict (stable_key) do update set subject_entity_id=excluded.subject_entity_id, statement=excluded.statement, language_code=excluded.language_code, claim_kind=excluded.claim_kind, evidence_class=excluded.evidence_class, confidence=excluded.confidence, applicability=excluded.applicability, uncertainty_note=excluded.uncertainty_note, rights_lane=excluded.rights_lane, publication_state=excluded.publication_state;

with input(stable_key, statement, language_code, confidence, citation_ordinal, chapter, verse, source_ordinal, source_span_sha256, translation_note, uncertainty_note) as (values
  ('durga-devimahatmya-semantic-madhu-kaitabha-episode-en', 'Within this exact provider-revision boundary, Devī Māhātmya chapter 81 presents the narrative of the Goddess acting so that Madhu and Kaiṭabha might be slain.', 'en', 0.9, 68, 81, 68, 68, '9674ccdc9085abf16771972b1a0baf50062d4fb67a85864a5a1330d105d9ce3e', 'Tāmasī is translated as dark while retaining the Sanskrit category in Hindi; it should not be reduced to a moral judgment.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 81, verse 68. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-madhu-kaitabha-episode-hi', 'इस सटीक प्रदाता-संशोधन सीमा में देवीमाहात्म्य का अध्याय 81 देवी द्वारा मधु और कैटभ के वध की दिशा में किए गए कार्य का आख्यान प्रस्तुत करता है।', 'hi', 0.9, 68, 81, 68, 68, '9674ccdc9085abf16771972b1a0baf50062d4fb67a85864a5a1330d105d9ce3e', 'Tāmasī is translated as dark while retaining the Sanskrit category in Hindi; it should not be reduced to a moral judgment.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 81, verse 68. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-mahishasura-episode-en', 'Within this exact provider-revision boundary, Devī Māhātmya chapter 83 presents the Goddess''s destruction of Mahiṣa together with his army and allies.', 'en', 0.97, 189, 83, 41, 189, '0acdefb9b761bf80c8c2d9a31f26859889e3c67dcf77646e312284e4215acda3', 'The narrative’s trilokya-delusion claim remains explicitly attributed to this source.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 83, verse 41. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-mahishasura-episode-hi', 'इस सटीक प्रदाता-संशोधन सीमा में देवीमाहात्म्य का अध्याय 83 देवी द्वारा महिष, उसकी सेना और उसके सहयोगियों के विनाश का आख्यान प्रस्तुत करता है।', 'hi', 0.97, 189, 83, 41, 189, '0acdefb9b761bf80c8c2d9a31f26859889e3c67dcf77646e312284e4215acda3', 'The narrative’s trilokya-delusion claim remains explicitly attributed to this source.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 83, verse 41. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-shumbha-episode-en', 'Within this exact provider-revision boundary, Devī Māhātmya chapter 84 introduces the Goddess''s renewed manifestation for the slaying of Śumbha.', 'en', 0.98, 229, 84, 37, 229, '6942ec592593a86e4d6b94c5fddd009b9a90f79f720f42c473b2194f3269fbd4', 'The source names the next manifestation’s bodily origin and adversaries, defining the transition to the following episode.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 84, verse 37. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-shumbha-episode-hi', 'इस सटीक प्रदाता-संशोधन सीमा में देवीमाहात्म्य का अध्याय 84 शुम्भ के वध के लिए देवी के पुनः प्रकट होने का आख्यान आरम्भ करता है।', 'hi', 0.98, 229, 84, 37, 229, '6942ec592593a86e4d6b94c5fddd009b9a90f79f720f42c473b2194f3269fbd4', 'The source names the next manifestation’s bodily origin and adversaries, defining the transition to the following episode.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 84, verse 37. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-nishumbha-episode-en', 'Within this exact provider-revision boundary, Devī Māhātmya chapter 84 introduces the Goddess''s renewed manifestation for the slaying of Niśumbha.', 'en', 0.98, 229, 84, 37, 229, '6942ec592593a86e4d6b94c5fddd009b9a90f79f720f42c473b2194f3269fbd4', 'The source names the next manifestation’s bodily origin and adversaries, defining the transition to the following episode.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 84, verse 37. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.'),
  ('durga-devimahatmya-semantic-nishumbha-episode-hi', 'इस सटीक प्रदाता-संशोधन सीमा में देवीमाहात्म्य का अध्याय 84 निशुम्भ के वध के लिए देवी के पुनः प्रकट होने का आख्यान आरम्भ करता है।', 'hi', 0.98, 229, 84, 37, 229, '6942ec592593a86e4d6b94c5fddd009b9a90f79f720f42c473b2194f3269fbd4', 'The source names the next manifestation’s bodily origin and adversaries, defining the transition to the following episode.', 'Devam source-bounded narrative index for one exact Sanskrit Wikisource provider revision at chapter 84, verse 37. It is not a source-original translation, identified print edition, critical recension, complete Devimahatmya or Shakta tradition, festival origin, ritual authority, historical claim, or label for living people or groups.')
)
insert into public.claim_evidence (claim_id, passage_id, evidence_role, note)
select c.id, p.id, 'supports', jsonb_build_object(
  'contract', 'DEVAM_SOURCE_BOUNDED_SEMANTIC_GRAPH_V1', 'pack_id', 'durga-devimahatmya-semantic-graph-v1', 'pack_sha256', '0dcd7f37ebdcb3dc5ad4049aafa0cb5b7668884bbb29e6b742e32fe7a0b75c34',
  'source_sha256', 'c7fe701aedeedffde57a51b21aa4f8fec697a7922939fb59ffa985e22cc9b7ae', 'source_ordinal', i.source_ordinal, 'source_span_sha256', i.source_span_sha256,
  'citation_ordinal', i.citation_ordinal, 'chapter', i.chapter, 'verse', i.verse, 'source_boundary', 'this_exact_three_revision_source_universe_only',
  'translation_claim_stable_key', 'durga-devimahatmya-wikisource-translation-' || lpad(i.citation_ordinal::text, 4, '0') || '-' || i.language_code,
  'translation_is_source_original', false, 'translation_note', i.translation_note, 'source_payload_duplicated', false)::text
from input i join public.claims c on c.stable_key=i.stable_key
join public.source_objects s on s.sha256='c7fe701aedeedffde57a51b21aa4f8fec697a7922939fb59ffa985e22cc9b7ae'
join public.passages p on p.source_object_id=s.id and p.source_ordinal=i.source_ordinal and p.span_sha256=i.source_span_sha256
on conflict (claim_id, passage_id, evidence_role) do update set note=excluded.note;

with input(object_slug, predicate, claim_key) as (values
  ('madhu-kaitabha', 'contains_narrative_of', 'durga-devimahatmya-semantic-madhu-kaitabha-episode-en'),
  ('mahishasura', 'contains_narrative_of', 'durga-devimahatmya-semantic-mahishasura-episode-en'),
  ('shumbha', 'contains_narrative_of', 'durga-devimahatmya-semantic-shumbha-episode-en'),
  ('nishumbha', 'contains_narrative_of', 'durga-devimahatmya-semantic-nishumbha-episode-en')
)
insert into public.relationships (subject_entity_id, predicate, object_entity_id, claim_id, applicability, rights_lane, publication_state)
select subject.id, i.predicate, object.id, c.id,
  jsonb_build_object('pack_id', 'durga-devimahatmya-semantic-graph-v1', 'pack_sha256', '0dcd7f37ebdcb3dc5ad4049aafa0cb5b7668884bbb29e6b742e32fe7a0b75c34', 'source_boundary', 'this_exact_three_revision_source_universe_only',
    'relationship_kind', 'text_contains_narrative_identity', 'not_historical_or_universal', true),
  'derivative_allowed', 'published'
from input i cross join public.entities subject join public.entities object on object.slug=i.object_slug join public.claims c on c.stable_key=i.claim_key
where subject.slug='devi-mahatmya'
on conflict (subject_entity_id, predicate, object_entity_id, claim_id) do update set applicability=excluded.applicability, rights_lane=excluded.rights_lane, publication_state=excluded.publication_state;

do $$
begin
  if (select count(*) from public.entities where slug=any(array['madhu-kaitabha', 'mahishasura', 'shumbha', 'nishumbha']) and rights_lane='derivative_allowed' and publication_state='published') <> 4 then raise exception 'Devimahatmya semantic entity verification failed'; end if;
  if (select count(*) from public.entity_names n join public.entities e on e.id=n.entity_id where e.slug=any(array['madhu-kaitabha', 'mahishasura', 'shumbha', 'nishumbha']) and n.is_preferred) <> 12 then raise exception 'Devimahatmya semantic preferred-name verification failed'; end if;
  if (select count(*) from public.claims where stable_key like 'durga-devimahatmya-semantic-%' and claim_kind='source_bounded_narrative_index' and evidence_class='devam_synthesis' and rights_lane='derivative_allowed' and publication_state='published') <> 8 then raise exception 'Devimahatmya semantic claim verification failed'; end if;
  if (select count(*) from public.claim_evidence ce join public.claims c on c.id=ce.claim_id where c.stable_key like 'durga-devimahatmya-semantic-%' and ce.evidence_role='supports') <> 8 then raise exception 'Devimahatmya semantic evidence verification failed'; end if;
  if (select count(*) from public.relationships r join public.entities s on s.id=r.subject_entity_id join public.entities o on o.id=r.object_entity_id join public.claims c on c.id=r.claim_id where s.slug='devi-mahatmya' and o.slug=any(array['madhu-kaitabha', 'mahishasura', 'shumbha', 'nishumbha']) and r.predicate='contains_narrative_of' and c.stable_key like 'durga-devimahatmya-semantic-%' and r.rights_lane='derivative_allowed' and r.publication_state='published') <> 4 then raise exception 'Devimahatmya semantic relationship verification failed'; end if;
end $$;

commit;
